config/routes.rb
Rails.application.routes.draw do
  root to: 'videos#index'
  post 'videos', to: 'videos#create'
  get 'videos/new', to: 'videos#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord
  has_one_attached :video
  has_one_attached :thumbnail

  validates :title, presence: true
  validates :category, presence: true
  validates_presence_of :video, message: 'upload is mandatory.'
  validate :video_type
  validate :video_size
  validate :thumbnail_type

  enum category: { exercise: 0, education: 1, recipe: 2 }

  private

  def video_type
    return unless video.attached? && !video.content_type.in?(%w[video/mp4 video/mov])

    errors.add(:video, ' must be in MP4 or MOV type.')
  end

  def video_size
    return unless video.attached? && video.byte_size > 200.megabytes

    errors.add(:video, 'should be less than 200MB.')
  end

  def thumbnail_type
    return unless thumbnail.attached? && !thumbnail.attachment.blob.content_type.in?(%w[image/png image/jpeg image/jpg])

    errors.add(:thumbnail, 'must be an image file.')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos or /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        save_images if @video.thumbnail.attached?
        format.html { redirect_to root_path, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def video_params
    params.require(:video).permit(:title, :category, :video, :thumbnail)
  end

  def save_images
    @video.update(image_64: url_for(@video.thumbnail.variant(resize: '64x64')))
    @video.update(image_128: url_for(@video.thumbnail.variant(resize: '128x128')))
    @video.update(image_256: url_for(@video.thumbnail.variant(resize: '256x256')))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LIMA20220319</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://vjs.zencdn.net/7.18.1/video-js.css" rel="stylesheet" />
    <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>

    <script src="https://kit.fontawesome.com/2375142c1c.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
    <script src="https://vjs.zencdn.net/7.18.1/video.min.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
    <% if video.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <p>
          <%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:
        </p>
        <ul>
          <% video.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field mt-5">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field mt-3">
    <%= form.label :video %>
    <%= form.file_field :video %>
  </div>

  <div class="field mt-3">
    <%= form.label :thumbnail %>
    <%= form.file_field :thumbnail %>
  </div>

  <div class="field mt-3">
    <%= form.label :category %>
    <%= form.select :category, Video.categories.keys.to_a %>
  </div>

  <%= form.submit class: 'btn btn-primary mt-3' %>
<% end %>

app/views/videos/index.html.erb
<div class="container my-5">
  <div class="d-flex justify-content-end">
    <%= link_to 'Upload', videos_new_path, class: 'btn btn-primary' %>
  </div>

  <div class="row mt-4">
    <% @videos.each do |video| %>
      <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
        <div class="shadow">
          <div title="<%= video.title %>" class="card">
            <video
              id="my-video"
              class="video-js card-m mt-3"
              controls
              preload="auto"
              width="256"
              height="256"
              poster="<%= video.thumbnail.attached? ? url_for(video.thumbnail) : url_for(video.video.preview(resize: "256x256")) %>"
              data-setup=""
            >
              <source src="<%= url_for(video.video) %>" type="video/mp4" />
              <source src="<%= url_for(video.video) %>" type="video/mov" />
            </video>
            <div class="card-body">
              <h5 class="card-title"> <i class="fa-solid fa-video"></i> Title: <%= video.title %></h5>
              <p class="card-text">Category: <%= video.category %></p>
            </div>
          </div>
        </div>	
      </div>
    <% end %>
  </div>
</div>

app/views/videos/new.html.erb
<div class="container my-5 py-5">
  <%= link_to root_path, :class => "icon-all my-5 text-decoration-none" do %>
    <i class="fa-solid fa-backward"></i></i> Back
  <% end %>
        
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-success p-2 text-dark bg-opacity-10 rounded p-3 shadow">
        <h3 class='text-center'>New Video</h3>
        <%= render 'form', video: @video %>
      </div>
    </div>
  </div>
</div>